version: '3.8'

services:
  mydb:
    image: yash02rajput/db-server:latest
    container_name: mydb-container
    ports:
      - "4000:4000"  
    volumes:
      - ./dbs:/app/dbs
    command: ["db-server", "4000"]
